{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saml-idp.fullname" . }}
  labels:
    {{- include "saml-idp.labels" . | nindent 4 }}
data:
  config.js: |
    module.exports = {
      metadata: {{ .Values.config.metadata | toJson }},
      user: {{ .Values.config.user | toJson }}
    };
{{- end }}
