{{- if .Values.idp.encryptAssertion -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saml-idp.fullname" . }}-encryption-cert
  labels:
    {{- include "saml-idp.labels" . | nindent 4 }}
type: Opaque
stringData:
  tls.crt: {{ required "idp.encryptionCert must be set when idp.encryptAssertion is true" .Values.idp.encryptionCert | quote }}
{{- end }}
