apiVersion: v2
name: saml-idp
description: A test SAML 2.0 Identity Provider with switchable users and signing certificates
type: application
version: 0.0.0
appVersion: "0.1.0"
keywords:
  - saml
  - identity-provider
  - authentication
  - testing
home: https://github.com/irgeek/saml-idp-helm
sources:
  - https://github.com/irgeek/saml-idp-helm
maintainers:
  - name: irgeek
    url: https://github.com/irgeek
